#!/usr/bin/env python3
"""Generate the compressed blobs the hardware benchmark inflates.

Why this exists rather than compressing on the device: the ROM's `tdefl` cannot
run on this chip. `esp_rom/include/miniz.h` defines MINIZ_NO_MALLOC (line 39),
and a `tdefl_compressor` is about 130 KB -- a 32 KB dictionary, a 64 KB LZ code
buffer and a 64 KB hash table. The device had 112 KB of free internal heap when
the benchmark ran, so `tdefl_compress_mem_to_mem` returned 0 for every level and
the firmware reported four `compress_failed` skips and no cycle counts.

Inflating is the direction that matters anyway: the device only ever inflates.
Compressing here instead gives something on-device compression could not -- the
ratio becomes a chosen input rather than an outcome, so the benchmark can report
cycles per output byte against a spread of ratios rather than against whatever
one source happened to produce.

The source bytes are regenerated on the device by `bench_fill_source()`, which
must stay byte-for-byte identical to `fill_source()` below. The benchmark
inflates each blob and compares the result against that regenerated source, so a
drift between the two shows up as a failed check rather than as a plausible
cycle count.

    python3 tools/make_bench_blobs.py            # rewrite main/bench_blobs.h
    python3 tools/make_bench_blobs.py --check    # fail if it would change
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import zlib

# Four stripes of the product's geometry: 4 * AV_STRIPE_PIXELS = 4 * 3840.
SOURCE_BYTES = 15360

# The ratios to hit, each as (repeat_block, noise_every). A run of `repeat_block`
# bytes taken from a pseudo-random pattern repeats for the whole buffer, and
# every `noise_every`-th byte is replaced by fresh noise. The longer the block
# and the more frequent the noise, the worse the compression -- so these four
# walk from ratio ~8 down to ~2.
#
# Chosen by measuring, not by intent: the ratio each one actually reaches is
# reported below and stored in the header, and the first model tried -- mixing
# base and noise per byte -- turned out to reach only 1.35 at best, which is one
# end of the range rather than the spread the benchmark needs.
VARIANTS = (
    (1792, 0),    # ~7.8
    (1536, 61),   # ~5.2
    (512, 13),    # ~3.2
    (512, 7),     # ~2.3
)

# zlib level 6, which is what server/frames.py compresses the product's stripes
# with. Matching it means the decoder's input is shaped like the real thing.
LEVEL = 6


def fill_source(variant: tuple[int, int], n: int = SOURCE_BYTES) -> bytearray:
    """Mirror of bench_fill_source() in main/av_player.c. Keep the two in step.

    C's uint32_t wraps; Python's integers do not, so the multiply is masked to
    32 bits explicitly. Getting this wrong produces blobs that inflate cleanly
    and then fail the device's comparison, which reads as a decoder fault rather
    than as a generator bug.
    """
    repeat_block, noise_every = variant
    x = 0x12345678

    def nxt() -> int:
        nonlocal x
        x = (x * 1103515245 + 12345) & 0xFFFFFFFF
        return (x >> 16) & 0xFF

    pattern = bytes(nxt() for _ in range(repeat_block))
    out = bytearray(n)
    for i in range(n):
        if noise_every and i % noise_every == 0:
            out[i] = nxt()
        else:
            out[i] = pattern[i % repeat_block]
    return out


def render() -> str:
    lines = [
        "// Generated by tools/make_bench_blobs.py -- do not edit by hand.",
        "//",
        "// Compressed stripes for the hardware benchmark to inflate, one per",
        "// compression ratio. The device regenerates the source with",
        "// bench_fill_source() and compares, so the comment above each blob",
        "// records the ratio this file actually achieved rather than a target.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define BENCH_BLOB_SOURCE_BYTES {SOURCE_BYTES}u",
        "",
        "typedef struct {",
        "    unsigned repeat_block;  // bench_fill_source() arguments, in order",
        "    unsigned noise_every;",
        "    const uint8_t *data;    // zlib stream, header and adler32 included",
        "    size_t length;",
        "    unsigned ratio_x1000;   // source bytes / compressed bytes, measured here",
        "} bench_blob_t;",
        "",
    ]
    entries = []
    for index, variant in enumerate(VARIANTS):
        source = fill_source(variant)
        blob = zlib.compress(bytes(source), LEVEL)
        ratio = len(source) * 1000 // len(blob)
        name = f"bench_blob_{index}"
        lines.append(
            f"// repeat_block={variant[0]} noise_every={variant[1]} level={LEVEL}: "
            f"{len(source)} -> {len(blob)} bytes, ratio {ratio / 1000:.2f}"
        )
        lines.append(f"static const uint8_t {name}[{len(blob)}] = {{")
        for i in range(0, len(blob), 12):
            chunk = ", ".join(f"0x{b:02x}" for b in blob[i : i + 12])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
        entries.append((variant, name, len(blob), ratio))

    lines.append("static const bench_blob_t BENCH_BLOBS[] = {")
    for variant, name, length, ratio in entries:
        lines.append(
            f"    {{ {variant[0]}u, {variant[1]}u, {name}, {length}u, {ratio}u }},"
            f"  // ratio {ratio / 1000:.2f}"
        )
    lines.append("};")
    lines.append(
        "#define BENCH_BLOB_COUNT (sizeof(BENCH_BLOBS) / sizeof(BENCH_BLOBS[0]))"
    )
    lines.append("")
    return "\n".join(lines)


def parse_committed(text: str) -> list[tuple[tuple[int, int], bytes]]:
    """Read back the blobs a committed header actually carries.

    Returns (variant, raw bytes) in file order. Regex rather than a C parser:
    the file this script writes is the only thing it is ever asked to read, and
    its shape is fixed above.
    """
    arrays = {}
    for match in re.finditer(
        r"static const uint8_t (\w+)\[(\d+)\] = \{(.*?)\};", text, re.S
    ):
        name, declared, body = match.group(1), int(match.group(2)), match.group(3)
        data = bytes(int(b, 16) for b in re.findall(r"0x([0-9a-f]{2})", body))
        if len(data) != declared:
            raise ValueError(f"{name}: declared {declared} bytes, found {len(data)}")
        arrays[name] = data

    table = re.search(r"BENCH_BLOBS\[\] = \{(.*?)\};", text, re.S)
    if not table:
        raise ValueError("BENCH_BLOBS[] not found")
    entries = []
    row = re.compile(
        r"\{\s*(\d+)u,\s*(\d+)u,\s*(\w+),\s*(\d+)u,\s*(\d+)u\s*\}"
    )
    for match in row.finditer(table.group(1)):
        repeat_block, noise_every, name, length, _ratio = match.groups()
        if name not in arrays:
            raise ValueError(f"BENCH_BLOBS references {name}, which is not defined")
        data = arrays[name]
        if len(data) != int(length):
            raise ValueError(f"{name}: table says {length}, array holds {len(data)}")
        entries.append(((int(repeat_block), int(noise_every)), data))
    return entries


def check(target: pathlib.Path) -> int:
    """Verify the committed header decodes to what bench_fill_source() produces.

    Deliberately does NOT recompress and compare bytes. zlib's *output* for a
    given input and level is not guaranteed identical across implementations or
    versions -- zlib 1.3 and zlib-ng differ -- so a byte comparison would fail
    on a machine that is not this one while the firmware was perfectly correct.
    An instrument that fails for its own reasons is worse than none, and this
    project has already been bitten once by a check that was wrong in the
    flattering direction.

    Decompression is the other way round: inflate is fully specified, so the
    bytes that come out are the same everywhere. What is verified is therefore
    the fact that matters -- that each committed blob inflates to exactly the
    stream the device will regenerate and compare against.
    """
    if not target.exists():
        print(f"{target} is missing; run tools/make_bench_blobs.py", file=sys.stderr)
        return 1
    text = target.read_text(encoding="utf-8")
    try:
        committed = parse_committed(text)
    except ValueError as exc:
        print(f"{target} cannot be read back: {exc}", file=sys.stderr)
        return 1

    problems = []
    if len(committed) != len(VARIANTS):
        problems.append(
            f"header holds {len(committed)} blobs, the generator defines {len(VARIANTS)}"
        )
    for (variant, blob) in committed:
        try:
            plain = zlib.decompress(blob)
        except zlib.error as exc:
            problems.append(f"variant {variant}: does not inflate ({exc})")
            continue
        if plain != bytes(fill_source(variant, len(plain))):
            problems.append(f"variant {variant}: inflates to something other than the mirror")
        elif len(plain) != SOURCE_BYTES:
            problems.append(f"variant {variant}: inflates to {len(plain)}, wanted {SOURCE_BYTES}")

    if problems:
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        print(f"{target} is stale; run tools/make_bench_blobs.py", file=sys.stderr)
        return 1
    print(f"{target} is consistent with bench_fill_source()")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed header without rewriting it",
    )
    args = parser.parse_args()

    target = pathlib.Path(__file__).resolve().parent.parent / "main" / "bench_blobs.h"

    if args.check:
        return check(target)

    target.write_text(render(), encoding="utf-8")
    print(f"wrote {target}")
    for variant in VARIANTS:
        source = fill_source(variant)
        blob = zlib.compress(bytes(source), LEVEL)
        print(
            f"  block={variant[0]:5d} noise={variant[1]:3d}  {len(source)} -> "
            f"{len(blob):5d} bytes  ratio {len(source) / len(blob):.2f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
